### PR TITLE
Chapter Header added

### PR DESCRIPTION
**Pull request by anushkaGurjar99**

### CODE REVIEW

**Comment by suvratapte** [comment]
Hello Anushka, 

Thank you so much for making this change! :)
Although, I have a small suggestion. Do you think that writing just "1" would look better than writing "Chapter-1"?

The reason I have not included chapter numbers is because the file names themselves have chapter numbers. For example: "1-General-Overview-of-the-System.md". The file names show up on the top.

But I don't mind having chapter numbers in the titles as long as we include on the numbers instead of the "Chapter-" and then the numbers.

What do you think?

**Comment by anushkaGurjar99** [comment]
Definitely you make sense.
Maybe I personally feel it should be more descriptive so I added. Anyway,
it's okay ;-)

*Anushka Gurjar*

**Comment by suvratapte** [comment]
Great! Will you make the change then?

**Comment by anushkaGurjar99** [comment]
I have already done it.

**Comment by suvratapte** [comment]
No no, I mean going from "Chapter-1:" to just "1."

**Comment by anushkaGurjar99** [comment]
Yes, I have made local changes in forked repo.
But you can ignore that, I will close the pull request🙈


-- 
*Anushka Gurjar*

**Comment by suvratapte** [comment]
You can make another pull request with that change. I'll merge it. :)

**Comment by anushkaGurjar99** [comment]
Sure thanks.😁

-- 
*Anushka Gurjar*

**Pull request closed without merging**
